language: python
python:
  - '2.7'
  - '3.5'
install:
  - python setup.py install
  - pip install flake8
before_script: flake8 timeout.py test_timeout.py
script: python setup.py test
deploy:
  provider: pypi
  user: seemethere
  password:
    secure: SOc8pWTW47Lt6yApOumI7c0lOSTqrtVVXMbwVVERjCPlXLje6Reem4C6zlC8Wu8xk6IvyZet/BsD+3QdpLu3iV31u1tz1FMLlYwOFUyxMODhMO/sBQK8yZGzVqR2xMh0b72mfbTBp/81tK3oclFQ7tLtE3BahG83hu6D9JCczaMvQuimhFUWmxcZL2/DhhsOFBbvBzzCxc4XwIMNRe1SB6S5ImsnnFk08GXMi63xoCox1xGS2z/dOB8hmv5KxfSfMtoFqKxbhiwi05fAHwjWQlIy5+46vzb9Ywl5gc94usm/ZAxL95g/lM2XV42E5fpuz4Ggpuk+3HqgnH6RPtzN+kdk7uz+fdChQpVMIpW8m5ZVG6wfca1UOShrOvC8rMkjNawd3y+GX5AXOFnAfdkY1FkDT2qybJiHILpfQae0O/1WgLdhkNT76ibQgtSvoM9Ly/rxF4llJPwbsgiKa2EyP/dtZGMeZcFPZPLwOi+g96IyIRJIfJxiX7qRLVnzhcYnRT8ku85iWFqLmPfNKjcBrQzarB7VI44g2uQYmo+D12+kfPxPLFeAutC4ljNZqvp/QDJg3xFAO/btXI22GG8YTs3cy2ASJu1koySGYAHeOZ5EBCfYx6TfPmWXOIWVYh7A96zUbBr09zISAzYPny/o12QRceg8squGzhRbxt8FUKI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: seemethere/timeout.stuff
